// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using obg.DataAccess.Context;

namespace obg.DataAccess.Migrations
{
    [DbContext(typeof(ObgContext))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("obg.Domain.Entities.Demand", b =>
                {
                    b.Property<string>("IdDemand")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("IdDemand");

                    b.ToTable("Demands");
                });

            modelBuilder.Entity("obg.Domain.Entities.Invitation", b =>
                {
                    b.Property<string>("IdInvitation")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PharmacyName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("UserCode")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserRole")
                        .HasColumnType("int");

                    b.HasKey("IdInvitation");

                    b.HasIndex("PharmacyName");

                    b.ToTable("Invitations");
                });

            modelBuilder.Entity("obg.Domain.Entities.Medicine", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PharmacyName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Prescription")
                        .HasColumnType("bit");

                    b.Property<int>("Presentation")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("SymtompsItTreats")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unit")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Code");

                    b.HasIndex("PharmacyName");

                    b.ToTable("Medicines");
                });

            modelBuilder.Entity("obg.Domain.Entities.Petition", b =>
                {
                    b.Property<string>("IdPetition")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DemandIdDemand")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MedicineCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NewQuantity")
                        .HasColumnType("int");

                    b.HasKey("IdPetition");

                    b.HasIndex("DemandIdDemand");

                    b.ToTable("Petitions");
                });

            modelBuilder.Entity("obg.Domain.Entities.Pharmacy", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdministratorName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("OwnerName")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Name");

                    b.HasIndex("AdministratorName");

                    b.HasIndex("OwnerName");

                    b.ToTable("Pharmacies");
                });

            modelBuilder.Entity("obg.Domain.Entities.Purchase", b =>
                {
                    b.Property<string>("IdPurchase")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<string>("BuyerEmail")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPurchase");

                    b.ToTable("Purchases");
                });

            modelBuilder.Entity("obg.Domain.Entities.PurchaseLine", b =>
                {
                    b.Property<string>("IdPurchaseLine")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MedicineCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MedicineQuantity")
                        .HasColumnType("int");

                    b.Property<string>("PurchaseIdPurchase")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IdPurchaseLine");

                    b.HasIndex("PurchaseIdPurchase");

                    b.ToTable("PurchaseLines");
                });

            modelBuilder.Entity("obg.Domain.Entities.Session", b =>
                {
                    b.Property<string>("IdSession")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdSession");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("obg.Domain.Entities.User", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegisterDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Name");

                    b.ToTable("Users");

                    b.HasDiscriminator<string>("Discriminator").HasValue("User");
                });

            modelBuilder.Entity("obg.Domain.Entities.Administrator", b =>
                {
                    b.HasBaseType("obg.Domain.Entities.User");

                    b.HasDiscriminator().HasValue("Administrator");
                });

            modelBuilder.Entity("obg.Domain.Entities.Employee", b =>
                {
                    b.HasBaseType("obg.Domain.Entities.User");

                    b.Property<string>("PharmacyName")
                        .HasColumnType("nvarchar(450)");

                    b.HasIndex("PharmacyName");

                    b.HasDiscriminator().HasValue("Employee");
                });

            modelBuilder.Entity("obg.Domain.Entities.Owner", b =>
                {
                    b.HasBaseType("obg.Domain.Entities.User");

                    b.HasDiscriminator().HasValue("Owner");
                });

            modelBuilder.Entity("obg.Domain.Entities.Invitation", b =>
                {
                    b.HasOne("obg.Domain.Entities.Pharmacy", "Pharmacy")
                        .WithMany()
                        .HasForeignKey("PharmacyName");

                    b.Navigation("Pharmacy");
                });

            modelBuilder.Entity("obg.Domain.Entities.Medicine", b =>
                {
                    b.HasOne("obg.Domain.Entities.Pharmacy", null)
                        .WithMany("Medicines")
                        .HasForeignKey("PharmacyName");
                });

            modelBuilder.Entity("obg.Domain.Entities.Petition", b =>
                {
                    b.HasOne("obg.Domain.Entities.Demand", null)
                        .WithMany("Petitions")
                        .HasForeignKey("DemandIdDemand");
                });

            modelBuilder.Entity("obg.Domain.Entities.Pharmacy", b =>
                {
                    b.HasOne("obg.Domain.Entities.Administrator", null)
                        .WithMany("Pharmacies")
                        .HasForeignKey("AdministratorName");

                    b.HasOne("obg.Domain.Entities.Owner", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerName");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("obg.Domain.Entities.PurchaseLine", b =>
                {
                    b.HasOne("obg.Domain.Entities.Purchase", null)
                        .WithMany("PurchaseLines")
                        .HasForeignKey("PurchaseIdPurchase");
                });

            modelBuilder.Entity("obg.Domain.Entities.Employee", b =>
                {
                    b.HasOne("obg.Domain.Entities.Pharmacy", null)
                        .WithMany("Employees")
                        .HasForeignKey("PharmacyName");
                });

            modelBuilder.Entity("obg.Domain.Entities.Demand", b =>
                {
                    b.Navigation("Petitions");
                });

            modelBuilder.Entity("obg.Domain.Entities.Pharmacy", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("Medicines");
                });

            modelBuilder.Entity("obg.Domain.Entities.Purchase", b =>
                {
                    b.Navigation("PurchaseLines");
                });

            modelBuilder.Entity("obg.Domain.Entities.Administrator", b =>
                {
                    b.Navigation("Pharmacies");
                });
#pragma warning restore 612, 618
        }
    }
}
